using UnityEngine;
using System.IO;
using System.Collections.Generic;

public class MapLoader : MonoBehaviour
{
    [Header("Data Settings")]
    public string jsonFileName = "ShopData_AutoGenerated.json";

    void Start()
    {
        LoadAndSpawnMasterData();
    }

    public void LoadAndSpawnMasterData()
    {
        string filePath = Path.Combine(Application.streamingAssetsPath, jsonFileName);

        if (File.Exists(filePath))
        {
            string jsonText = File.ReadAllText(filePath);
            // 기존 ShopDataWrapper가 아닌 MasterDataWrapper로 파싱합니다.
            MasterDataWrapper masterData = JsonUtility.FromJson<MasterDataWrapper>(jsonText);

            if (masterData == null) return;

            // 1. 플레이어 위치 복구
            RestorePlayerPosition(masterData);

            // 2. 가구 배치
            if (masterData.furnitureData != null)
            {
                foreach (var entity in masterData.furnitureData)
                {
                    // 좌표가 (0,0,0)인 데이터는 배치되지 않은 것이므로 스킵합니다.
                    if (entity.position.x == 0 && entity.position.y == 0 && entity.position.z == 0)
                        continue;

                    SpawnFurniture(entity);
                }
            }
            Debug.Log("<color=green>통합 데이터 로드 완료!</color>");
        }
    }

    private void RestorePlayerPosition(MasterDataWrapper data)
    {
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null && data.playerPosition != null)
        {
            // CharacterController가 있다면 일시적으로 끄고 이동해야 씹히지 않습니다.
            CharacterController cc = player.GetComponent<CharacterController>();
            if (cc != null) cc.enabled = false;

            player.transform.position = data.playerPosition.ToVector3();
            player.transform.eulerAngles = new Vector3(0, data.playerRotation, 0);

            if (cc != null) cc.enabled = true;
            Debug.Log("플레이어 위치 복구 완료.");
        }
    }

    private void SpawnFurniture(FurnitureEntity entity)
    {
        string fullPath = $"{entity.folderPath}/{entity.prefabName}";
        GameObject prefab = Resources.Load<GameObject>(fullPath);

        if (prefab != null)
        {
            GameObject instance = Instantiate(prefab,
                entity.position.ToVector3(),
                Quaternion.Euler(0, entity.rotation, 0));

            instance.transform.localScale = entity.scale.ToVector3();
            instance.name = entity.id;

            // 데이터 보관을 위해 홀더 부착
            var holder = instance.AddComponent<FurnitureDataHolder>();
            holder.data = entity;
        }
    }
}