using UnityEngine;
using System.IO;
using System.Collections.Generic;

public class MapLoader : MonoBehaviour
{
    [Header("Data Settings")]
    public string jsonFileName = "ShopData_AutoGenerated.json";

    void Start()
    {
        LoadAndSpawnMap();
    }

    public void LoadAndSpawnMap()
    {
        string filePath = Path.Combine(Application.streamingAssetsPath, jsonFileName);

        if (File.Exists(filePath))
        {
            string jsonText = File.ReadAllText(filePath);
            ShopDataWrapper data = JsonUtility.FromJson<ShopDataWrapper>(jsonText);

            if (data == null || data.furnitureData == null) return;

            int spawnCount = 0;
            foreach (var entity in data.furnitureData)
            {
                // 좌표가 (0,0,0)인 항목은 배치되지 않은 것으로 간주하여 스킵
                if (entity.position.x == 0 && entity.position.y == 0 && entity.position.z == 0)
                    continue;

                SpawnFurniture(entity);
                spawnCount++;
            }

            Debug.Log($"<color=green>맵 로딩 완료: {spawnCount}개의 가구 배치됨</color>");
        }
    }

    void SpawnFurniture(FurnitureEntity entity)
    {
        string fullPath = $"{entity.folderPath}/{entity.prefabName}";
        GameObject prefab = Resources.Load<GameObject>(fullPath);

        if (prefab != null)
        {
            // [통일] 모든 프리팹은 저장된 위치, 회전, 스케일 값으로 생성됩니다.
            GameObject instance = Instantiate(prefab,
                entity.position.ToVector3(),
                Quaternion.Euler(0, entity.rotation, 0));

            instance.transform.localScale = entity.scale.ToVector3();
            instance.name = entity.id;

            // 데이터 관리용 홀더만 부착 (컴포넌트 자동 추가 로직 삭제)
            var holder = instance.AddComponent<FurnitureDataHolder>();
            holder.data = entity;
        }
        else
        {
            Debug.LogWarning($"프리팹 로드 실패: {fullPath}");
        }
    }
}