using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;

public class JsonDataExporter : EditorWindow
{
    [MenuItem("Tools/Export Prefabs to JSON")]
    public static void ShowWindow()
    {
        GetWindow<JsonDataExporter>("JSON Exporter");
    }

    private void OnGUI()
    {
        GUILayout.Label("원본 가구 도감(Library) 추출 도구", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        if (GUILayout.Button("Extract Prefabs and Save Library JSON", GUILayout.Height(40)))
        {
            ExportToLibrary();
        }

        EditorGUILayout.HelpBox("이 도구는 Resources 폴더의 모든 프리팹을 스캔하여 'FurnitureLibrary.json'을 만듭니다. 실제 배치 데이터와는 별개입니다.", MessageType.Info);
    }

    private void ExportToLibrary()
    {
        // 1. 경로 설정
        string relativePath = "ithappy/Furniture_Cute/Prefabs";
        string fullPath = Path.Combine(Application.dataPath, "Resources", relativePath);

        if (!Directory.Exists(Application.streamingAssetsPath))
            Directory.CreateDirectory(Application.streamingAssetsPath);

        if (!Directory.Exists(fullPath))
        {
            Debug.LogError("경로를 찾을 수 없습니다: " + fullPath);
            return;
        }

        MasterDataWrapper wrapper = new MasterDataWrapper();
        wrapper.furnitureData = new List<FurnitureEntity>();

        // 2. 모든 프리팹 검색
        string[] prefabFiles = Directory.GetFiles(fullPath, "*.prefab", SearchOption.AllDirectories);

        foreach (string file in prefabFiles)
        {
            string fileName = Path.GetFileNameWithoutExtension(file);

            // Resources 경로 추출
            string normalizedPath = file.Replace("\\", "/");
            string resourcesKeyword = "/Resources/";
            int resourcesIndex = normalizedPath.IndexOf(resourcesKeyword) + resourcesKeyword.Length;
            string directoryPath = Path.GetDirectoryName(normalizedPath).Replace("\\", "/");
            string resourcesPath = directoryPath.Substring(resourcesIndex);

            FurnitureEntity entity = new FurnitureEntity
            {
                id = fileName.ToUpper(), // 원본 도감용 기본 ID
                prefabName = fileName,
                folderPath = resourcesPath,
                type = fileName.Contains("Table") ? "Producer" :
                       fileName.Contains("Counter") ? "SellPoint" : "Decoration",
                position = new Vector3Data { x = 0, y = 0, z = 0 },
                // [필수 추가] 스케일 초기화 (1,1,1이 아니면 로드 시 안 보일 수 있음)
                scale = new Vector3Data { x = 1, y = 1, z = 1 },
                rotation = 0,
                price = 100,
                unlockOrder = 0,
                isUnlocked = false
            };

            wrapper.furnitureData.Add(entity);
        }

        // 3. 파일명 변경: ShopData_AutoGenerated -> FurnitureLibrary.json
        string json = JsonUtility.ToJson(wrapper, true);
        string savePath = Path.Combine(Application.streamingAssetsPath, "FurnitureLibrary.json");
        File.WriteAllText(savePath, json);

        AssetDatabase.Refresh();
        Debug.Log($"<color=yellow>가구 도감(FurnitureLibrary.json) 생성 완료! ({wrapper.furnitureData.Count}개)</color>");
    }
}