using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;

public class JsonDataExporter : EditorWindow
{
    [MenuItem("Tools/Export Prefabs to JSON")]
    public static void ShowWindow()
    {
        GetWindow<JsonDataExporter>("JSON Exporter");
    }

    private void OnGUI()
    {
        GUILayout.Label("Prefab 데이터 추출 도구", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        if (GUILayout.Button("Extract Prefabs and Save JSON", GUILayout.Height(40)))
        {
            ExportToJson();
        }
    }

    private void ExportToJson()
    {
        // 1. 경로 설정
        string relativePath = "ithappy/Furniture_Cute/Prefabs";
        string fullPath = Path.Combine(Application.dataPath, "Resources", relativePath);

        if (!Directory.Exists(Application.streamingAssetsPath))
            Directory.CreateDirectory(Application.streamingAssetsPath);

        if (!Directory.Exists(fullPath))
        {
            Debug.LogError("경로를 찾을 수 없습니다: " + fullPath);
            return;
        }

        ShopDataWrapper wrapper = new ShopDataWrapper();
        wrapper.furnitureData = new List<FurnitureEntity>(); // 이름 일치 확인

        // 2. 모든 프리팹 검색
        string[] prefabFiles = Directory.GetFiles(fullPath, "*.prefab", SearchOption.AllDirectories);

        foreach (string file in prefabFiles)
        {
            string fileName = Path.GetFileNameWithoutExtension(file);

            // Resources 경로 추출
            string normalizedPath = file.Replace("\\", "/");
            string resourcesKeyword = "/Resources/";
            int resourcesIndex = normalizedPath.IndexOf(resourcesKeyword) + resourcesKeyword.Length;
            string directoryPath = Path.GetDirectoryName(normalizedPath).Replace("\\", "/");
            string resourcesPath = directoryPath.Substring(resourcesIndex);

            FurnitureEntity entity = new FurnitureEntity
            {
                id = fileName.ToUpper(),
                prefabName = fileName,
                folderPath = resourcesPath,
                type = fileName.Contains("Table") ? "Producer" :
                       fileName.Contains("Counter") ? "SellPoint" : "Decoration",
                position = new Vector3Data { x = 0, y = 0, z = 0 },
                rotation = 0,
                price = 100
            };

            wrapper.furnitureData.Add(entity);
        }

        // 3. JSON 저장
        string json = JsonUtility.ToJson(wrapper, true);
        string savePath = Path.Combine(Application.streamingAssetsPath, "ShopData_AutoGenerated.json");
        File.WriteAllText(savePath, json);

        AssetDatabase.Refresh();
        Debug.Log($"<color=yellow>JSON 생성 완료! ({wrapper.furnitureData.Count}개)</color>");
    }
}